version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.4-management
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - '5672:5672'
      - '15672:15672'
    labels:
      name: "rabbitmq"
    volumes:
    - "$PWD/rabbitmq/data/log:/data/log"
    - "$PWD/rabbitmq/data/mnesia:/data/mnesia"
    - "$PWD/rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
